### ISSUE TITLE
?slap

### ISSUE THREAD

**Issue by sinus-x** [sinus-x/rubbergoddess#221]
`slap` command. I'm not sure if it should be image reaction (like `pet`) is, or emoji (like `hug`), I'll leave it up to the command author.

**Comment by ozamed** [comment]
Can I do this?

**Comment by sinus-x** [comment]
Yeah, give it a go. If you're not familiar with the discord.py library, look around the `cogs/meme/meme.py` and add another function below the `hug()`. If you don't want to mess with emojis or images, feel free to use some ascii characters.

Make sure you work on `devel` branch and not the `master`.

**Comment by ozamed** [comment]
No problem, I'm bot developer. Thanks :)

**Comment by ozamed** [comment]
@sinus-x I made PR

**Comment by ozamed** [comment]
@sinus-x Can you please accept the PR?
